project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: _site

website:
  title: "Biotic responses to environmental change"
  description: "Website of the research group of Frank Pennekamp"
  site-url: https://frank-pennekamp.info
  repo-url: https://github.com/pennekampster/quarto_website
  navbar:
    right:
      - icon: email
        href: frank.pennekamp@ieu.uzh.ch
      - icon: scholar
        href: https://scholar.google.de/citations?user=yRx8FTsAAAAJ&hl=de
    left:
      - href: about.qmd
        text: Home
      - href: people.qmd
#      - href: research.qmd
      - href: publications/publications.qmd
        text: Publications
      - href: software.qmd

format:
  html:
    theme: cosmo
    css: styles.css



